SUPABASE_URL = "https://vhuakrgwypunyxgnvdwq.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZodWFrcmd3eXB1bnl4Z252ZHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NjUxODQsImV4cCI6MjA4NzE0MTE4NH0.CaH9nIyknXJeLpXI2nq2rXSOSHD_xvHJcFnAycyNz8I"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZodWFrcmd3eXB1bnl4Z252ZHdxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTU2NTE4NCwiZXhwIjoyMDg3MTQxMTg0fQ.Ia0IKlBGxxkN5tv6a5jeNXcwyzuRhRwEQaUya6PjPJg"
ADMIN_PASSWORD = "TravelJournalAdmin_"
BUCKET = "journal-images"